:experimental:
:commandkey: &#8984;
:toc: macro

= R2DBC and Spring Demo Steps

In this demo, I'll show how to use Spring WebFlux and R2DBC to provide reactive, non-blocking access to a relational database. You'll see how to build a secure, OAuth 2.0-protected, app and stream its data.

**Prerequisites:**

- https://sdkman.io/[Java 11+]
- An https://developer.okta.com[Okta Developer] Account (or the https://cli.okta.com/[Okta CLI])

TIP: The brackets at the end of some steps indicate the IntelliJ Live Templates to use. You can find the template definitions at https://github.com/mraible/idea-live-templates[mraible/idea-live-templates].

toc::[]

== Install Java 11

. Use SDKMAN to install Java 11:

  sdk install java

== Create a Spring Boot Project with R2DBC

Using https://start.spring.io/#!type=maven-project&language=java&platformVersion=2.5.6&packaging=jar&jvmVersion=11&groupId=com.okta.dev&artifactId=okta-r2dbc&name=okta-r2dbc&description=Spring%20Boot%20App%20for%20Okta%20%2B%20R2DBC&packageName=com.okta.dev.oktar2dbc&dependencies=lombok,data-jpa,data-r2dbc,webflux,okta,h2[start.spring.io], create an app with the following settings:

- Group: `com.okta.dev`
- Artifact: `okta-r2dbc`
- Name: `okta-r2dbc`
- Package: `com.okta.dev.oktar2dbc`
- Dependencies: JPA, R2DBC, Reactive Web, Okta, H2, Lombok

== Create an OpenID Connect Application

. Using the Okta CLI, run `okta register` to sign up for a new account. If you already have an account, run `okta login`. Then, run `okta apps create`.

. Select the default app name, or change it as you see fit. Choose **Web** and press **Enter**.

. Select **Okta Spring Boot Starter**. Accept the default Redirect URI values provided for you. That is, a Login Redirect of `http://localhost:8080/login/oauth2/code/okta` and a Logout Redirect of `http://localhost:8080`.

== Configure and Secure Your Reactive Spring Boot Application

. Open your IDE and edit your application's configuration file at `src/main/resources/application.properties`:
+
[source,properties]
----
okta.oauth2.issuer=https://MY_OKTA_DOMAIN.okta.com/oauth2/default
okta.oauth2.clientId=CLIENT_ID
okta.oauth2.clientSecret=CLIENT_SECRET

spring.r2dbc.url=r2dbc:h2:mem://./testdb
----
+
Make sure `MY_OKTA_DOMAIN`, `CLIENT_ID`, and `CLIENT_SECRET` are replaced with values from the Okta CLI.

. Open `OktaR2dbcApplication` and add the `@EnableWebFlux` and `@EnableR2dbcRepositories` annotations:
+
[source,java]
----
@EnableWebFlux
@EnableR2dbcRepositories
@SpringBootApplication
public class OktaR2dbcApplication { ... }
----

. Create a `UserEntity` in a new `database` package:
+
[source,java]
----
package com.okta.dev.oktar2dbc.database;

import lombok.Data;
import org.springframework.data.annotation.Id;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

@Data
public class UserEntity {
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE)
    private Long id;
    private String email;
    private String name;
}
----

. Define a reactive `R2dbcRepository` to manage this entity:
+
[source,java]
----
package com.okta.dev.oktar2dbc.database;

import org.springframework.data.r2dbc.repository.R2dbcRepository;
import org.springframework.stereotype.Repository;
import reactor.core.publisher.Flux;

@Repository
public interface UserRepository extends R2dbcRepository<UserEntity, Long> {
    Flux<UserEntity> findByEmail(String email);
}
----
+
Some major differences between this and the non-reactive `JpaRepository` should be noted:

- Methods like `findById()` which return one entity will instead return a `Mono<>` object.
- Methods like `findAll()` which return lists of entities will instead return a `Flux<>` object.

. Create a `UserDetails` and a `DbUserService` class in a new `domain` package. [`r2dbc-userdetails`, `r2dbc-userservice`]
+
The `DbUserService` handles requests from OAuth 2.0 to automatically load users into the database. The user's information will be created or updated on each login.

. Secure the application by creating a `config.SecurityConfig` class. [`r2dbc-security`]

== Create an HTML client to see your data

. Create a file at `src/main/resources/pages/index.html`

. Create a file at `src/main/resources/pages/protected.html`

. Create an `ApplicationRouter.java` class. [`r2dbc-router`]

. Create a file at `src/main/resources/schema.sql` to create a database schema. [`r2dbc-schema`]

. Add a `ConnectionFactoryInitializer` bean in `OktaR2dbcApplication` to automatically detect and execute this script on startup. [`r2dbc-init`]

. Open a terminal and run your app with `./mvnw spring-boot:run`

. Open `http://localhost:8080` to see the unprotected index page. Go to `/protected`. You'll prompted to log in with Okta, and after successfully authenticating, returned to the protected page.

== Stream Data to a Webpage Using R2DBC

. Create a `database.HeartbeatEntity` entity.

. Create a `database.HeartbeatRepository` repository class.

. Add the table definition for `HEARTBEAT_ENTITY` to `schema.sql`.

. Create a `service.HeartbeatService` class to generate and save heartbeats to the database.
+
The `create()` method is marked with Spring Boot's `@Scheduled` annotation, which will cause the method to be called asynchronously on a schedule you define. Specifying `fixedRate = 1000` means the method will execute every 1000 milliseconds (i.e. one second).

. To enable scheduling, add `@EnableScheduling` to the main `OktaR2dbcApplication` class.

. Open `ApplicationRouter` and modify the `route()` method to add a routing for `/heartbeats`.

. Modify `protected.html` to call this endpoint and stream its data with jQuery.

. Restart the app, go to `http://localhost:8080/protected`, and you'll see a streaming, constantly updating list of heartbeats.

== R2DBC for faster access!

💡 Find the code on GitHub: https://github.com/oktadev/okta-spring-boot-r2dbc-example[@oktadev/okta-spring-boot-r2dbc-example]

📗 Read the blog post: https://developer.okta.com/blog/2021/05/12/spring-boot-r2dbc[R2DBC and Spring for Non-Blocking Database Access]


