CREATE TABLE `USER_ENTITY` (
    `id` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `email` VARCHAR2,
    `name` VARCHAR2
);

CREATE TABLE `HEARTBEAT_ENTITY` (
    `id` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `timestamp` BIGINT NOT NULL,
    `username` VARCHAR2 NOT NULL,
    `text` VARCHAR2
);